name: build
on:
  push:
    tags:
      - 'v*' # Run on version tags for releases
    branches:
      - '*' # Run on all branch pushes
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history including tags
      - uses: volta-cli/action@v4

      # Check if pushing to master without a tag
      - name: Check for version tag on master
        if: github.ref == 'refs/heads/master'
        run: |
          if ! git describe --exact-match --tags HEAD 2>/dev/null; then
            echo "❌ Error: Pushes to master branch must include a version tag"
            echo "Please create a tag first: git tag v0.11.1 && git push origin master --tags"
            exit 1
          fi
          echo "✅ Version tag found: $(git describe --exact-match --tags HEAD)"

      - run: npm ci
      - run: npx ts-patch install -s
      - run: npm run lint
      - run: npm test
      - run: npm run build

      # Create draft releases for development branch
      - name: Create Draft Release (Development)
        if: github.ref == 'refs/heads/development'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            lib/**/*
            package.json
            README.md
          generate_release_notes: true
          tag_name: 'dev-${{ github.run_number }}'
          name: 'Development Build ${{ github.run_number }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create proper releases for version tags on master
      - name: Check if tag is on master
        id: check_master
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Check if the tag points to a commit that's on master
          if git branch --contains HEAD | grep -q master; then
            echo "on_master=true" >> $GITHUB_OUTPUT
          else
            echo "on_master=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release (Master)
        if: startsWith(github.ref, 'refs/tags/v') && steps.check_master.outputs.on_master == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lib/**/*
            package.json
            README.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
