name: build
on:
  push:
    tags:
      - 'v*' # Run on version tags for releases
    branches:
      - '*' # Run on all branch pushes
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history including tags
      - uses: volta-cli/action@v4

      - run: npm ci
      - run: npx ts-patch install -s
      - run: npm run lint
      - run: npm test
      - run: npm run build

      # Publish to npm on master branch
      - name: Publish to npm
        if: github.ref == 'refs/heads/master'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Create draft releases for development branch
      - name: Create Draft Release (Development)
        if: github.ref == 'refs/heads/development'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            lib/**/*
            package.json
            README.md
          generate_release_notes: true
          tag_name: 'dev-${{ github.run_number }}'
          name: 'Development Build ${{ github.run_number }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create proper releases for master branch
      - name: Create Release (Master)
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lib/**/*
            package.json
            README.md
          generate_release_notes: true
          tag_name: 'v${{ github.run_number }}'
          name: 'Release v${{ github.run_number }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
