name: build
on:
  push:
    tags:
      - 'v*' # Run on version tags for releases
    branches:
      - '*' # Run on all branch pushes
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - run: npm ci # Install ALL dependencies including devDependencies
      - run: npx ts-patch install -s # Set up ts-patch using npx
      - run: npm run lint
      - run: npm test
      - run: npm run build

      # Create release with built files
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lib/**/*
            package.json
            README.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
